[package]
name = "fsha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
indicatif = "0.17.6"
rand = "0.8.5"
rayon = "1.7.0"
sha2 = "0.10.7"
walkdir = "2.3.3"
